package com.stuSystem.manager.pojo;

import java.util.Date;

public class Announce {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Integer annouId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String annouName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_content
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String annouContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_auth
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String annouAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_link
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String annouLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_visited
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Integer annouVisited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.annou_intime
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Date annouIntime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_id
     *
     * @return the value of announce.annou_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Integer getAnnouId() {
        return annouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_id
     *
     * @param annouId the value for announce.annou_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouId(Integer annouId) {
        this.annouId = annouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_name
     *
     * @return the value of announce.annou_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getAnnouName() {
        return annouName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_name
     *
     * @param annouName the value for announce.annou_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouName(String annouName) {
        this.annouName = annouName == null ? null : annouName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_content
     *
     * @return the value of announce.annou_content
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getAnnouContent() {
        return annouContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_content
     *
     * @param annouContent the value for announce.annou_content
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouContent(String annouContent) {
        this.annouContent = annouContent == null ? null : annouContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_auth
     *
     * @return the value of announce.annou_auth
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getAnnouAuth() {
        return annouAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_auth
     *
     * @param annouAuth the value for announce.annou_auth
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouAuth(String annouAuth) {
        this.annouAuth = annouAuth == null ? null : annouAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_link
     *
     * @return the value of announce.annou_link
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getAnnouLink() {
        return annouLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_link
     *
     * @param annouLink the value for announce.annou_link
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouLink(String annouLink) {
        this.annouLink = annouLink == null ? null : annouLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_visited
     *
     * @return the value of announce.annou_visited
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Integer getAnnouVisited() {
        return annouVisited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_visited
     *
     * @param annouVisited the value for announce.annou_visited
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouVisited(Integer annouVisited) {
        this.annouVisited = annouVisited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.annou_intime
     *
     * @return the value of announce.annou_intime
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Date getAnnouIntime() {
        return annouIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.annou_intime
     *
     * @param annouIntime the value for announce.annou_intime
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setAnnouIntime(Date annouIntime) {
        this.annouIntime = annouIntime;
    }
}