package com.stuSystem.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public ClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(String value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(String value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(String value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(String value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(String value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLike(String value) {
            addCriterion("class_id like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotLike(String value) {
            addCriterion("class_id not like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<String> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<String> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(String value1, String value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(String value1, String value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassBossIsNull() {
            addCriterion("class_boss is null");
            return (Criteria) this;
        }

        public Criteria andClassBossIsNotNull() {
            addCriterion("class_boss is not null");
            return (Criteria) this;
        }

        public Criteria andClassBossEqualTo(String value) {
            addCriterion("class_boss =", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossNotEqualTo(String value) {
            addCriterion("class_boss <>", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossGreaterThan(String value) {
            addCriterion("class_boss >", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossGreaterThanOrEqualTo(String value) {
            addCriterion("class_boss >=", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossLessThan(String value) {
            addCriterion("class_boss <", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossLessThanOrEqualTo(String value) {
            addCriterion("class_boss <=", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossLike(String value) {
            addCriterion("class_boss like", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossNotLike(String value) {
            addCriterion("class_boss not like", value, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossIn(List<String> values) {
            addCriterion("class_boss in", values, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossNotIn(List<String> values) {
            addCriterion("class_boss not in", values, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossBetween(String value1, String value2) {
            addCriterion("class_boss between", value1, value2, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassBossNotBetween(String value1, String value2) {
            addCriterion("class_boss not between", value1, value2, "classBoss");
            return (Criteria) this;
        }

        public Criteria andClassStucountIsNull() {
            addCriterion("class_stuCount is null");
            return (Criteria) this;
        }

        public Criteria andClassStucountIsNotNull() {
            addCriterion("class_stuCount is not null");
            return (Criteria) this;
        }

        public Criteria andClassStucountEqualTo(Integer value) {
            addCriterion("class_stuCount =", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountNotEqualTo(Integer value) {
            addCriterion("class_stuCount <>", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountGreaterThan(Integer value) {
            addCriterion("class_stuCount >", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_stuCount >=", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountLessThan(Integer value) {
            addCriterion("class_stuCount <", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountLessThanOrEqualTo(Integer value) {
            addCriterion("class_stuCount <=", value, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountIn(List<Integer> values) {
            addCriterion("class_stuCount in", values, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountNotIn(List<Integer> values) {
            addCriterion("class_stuCount not in", values, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountBetween(Integer value1, Integer value2) {
            addCriterion("class_stuCount between", value1, value2, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassStucountNotBetween(Integer value1, Integer value2) {
            addCriterion("class_stuCount not between", value1, value2, "classStucount");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeIsNull() {
            addCriterion("class_createTime is null");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeIsNotNull() {
            addCriterion("class_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeEqualTo(Date value) {
            addCriterion("class_createTime =", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeNotEqualTo(Date value) {
            addCriterion("class_createTime <>", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeGreaterThan(Date value) {
            addCriterion("class_createTime >", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("class_createTime >=", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeLessThan(Date value) {
            addCriterion("class_createTime <", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("class_createTime <=", value, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeIn(List<Date> values) {
            addCriterion("class_createTime in", values, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeNotIn(List<Date> values) {
            addCriterion("class_createTime not in", values, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeBetween(Date value1, Date value2) {
            addCriterion("class_createTime between", value1, value2, "classCreatetime");
            return (Criteria) this;
        }

        public Criteria andClassCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("class_createTime not between", value1, value2, "classCreatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 09 08:44:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}