package com.stuSystem.manager.pojo;

import java.util.Date;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_boss
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private String classBoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_stuCount
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private Integer classStucount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_createTime
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private Date classCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_id
     *
     * @return the value of class.class_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_id
     *
     * @param classId the value for class.class_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_boss
     *
     * @return the value of class.class_boss
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getClassBoss() {
        return classBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_boss
     *
     * @param classBoss the value for class.class_boss
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setClassBoss(String classBoss) {
        this.classBoss = classBoss == null ? null : classBoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_stuCount
     *
     * @return the value of class.class_stuCount
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public Integer getClassStucount() {
        return classStucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_stuCount
     *
     * @param classStucount the value for class.class_stuCount
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setClassStucount(Integer classStucount) {
        this.classStucount = classStucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class_createTime
     *
     * @return the value of class.class_createTime
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public Date getClassCreatetime() {
        return classCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class_createTime
     *
     * @param classCreatetime the value for class.class_createTime
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setClassCreatetime(Date classCreatetime) {
        this.classCreatetime = classCreatetime;
    }
}