package com.stuSystem.manager.pojo;

import java.util.ArrayList;
import java.util.List;

public class CourserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public CourserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCourserIdIsNull() {
            addCriterion("courser_id is null");
            return (Criteria) this;
        }

        public Criteria andCourserIdIsNotNull() {
            addCriterion("courser_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourserIdEqualTo(String value) {
            addCriterion("courser_id =", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdNotEqualTo(String value) {
            addCriterion("courser_id <>", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdGreaterThan(String value) {
            addCriterion("courser_id >", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdGreaterThanOrEqualTo(String value) {
            addCriterion("courser_id >=", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdLessThan(String value) {
            addCriterion("courser_id <", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdLessThanOrEqualTo(String value) {
            addCriterion("courser_id <=", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdLike(String value) {
            addCriterion("courser_id like", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdNotLike(String value) {
            addCriterion("courser_id not like", value, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdIn(List<String> values) {
            addCriterion("courser_id in", values, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdNotIn(List<String> values) {
            addCriterion("courser_id not in", values, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdBetween(String value1, String value2) {
            addCriterion("courser_id between", value1, value2, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserIdNotBetween(String value1, String value2) {
            addCriterion("courser_id not between", value1, value2, "courserId");
            return (Criteria) this;
        }

        public Criteria andCourserNameIsNull() {
            addCriterion("courser_name is null");
            return (Criteria) this;
        }

        public Criteria andCourserNameIsNotNull() {
            addCriterion("courser_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourserNameEqualTo(String value) {
            addCriterion("courser_name =", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameNotEqualTo(String value) {
            addCriterion("courser_name <>", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameGreaterThan(String value) {
            addCriterion("courser_name >", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameGreaterThanOrEqualTo(String value) {
            addCriterion("courser_name >=", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameLessThan(String value) {
            addCriterion("courser_name <", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameLessThanOrEqualTo(String value) {
            addCriterion("courser_name <=", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameLike(String value) {
            addCriterion("courser_name like", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameNotLike(String value) {
            addCriterion("courser_name not like", value, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameIn(List<String> values) {
            addCriterion("courser_name in", values, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameNotIn(List<String> values) {
            addCriterion("courser_name not in", values, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameBetween(String value1, String value2) {
            addCriterion("courser_name between", value1, value2, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserNameNotBetween(String value1, String value2) {
            addCriterion("courser_name not between", value1, value2, "courserName");
            return (Criteria) this;
        }

        public Criteria andCourserTypeIsNull() {
            addCriterion("courser_type is null");
            return (Criteria) this;
        }

        public Criteria andCourserTypeIsNotNull() {
            addCriterion("courser_type is not null");
            return (Criteria) this;
        }

        public Criteria andCourserTypeEqualTo(Integer value) {
            addCriterion("courser_type =", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeNotEqualTo(Integer value) {
            addCriterion("courser_type <>", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeGreaterThan(Integer value) {
            addCriterion("courser_type >", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("courser_type >=", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeLessThan(Integer value) {
            addCriterion("courser_type <", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeLessThanOrEqualTo(Integer value) {
            addCriterion("courser_type <=", value, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeIn(List<Integer> values) {
            addCriterion("courser_type in", values, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeNotIn(List<Integer> values) {
            addCriterion("courser_type not in", values, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeBetween(Integer value1, Integer value2) {
            addCriterion("courser_type between", value1, value2, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("courser_type not between", value1, value2, "courserType");
            return (Criteria) this;
        }

        public Criteria andCourserDescIsNull() {
            addCriterion("courser_desc is null");
            return (Criteria) this;
        }

        public Criteria andCourserDescIsNotNull() {
            addCriterion("courser_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCourserDescEqualTo(String value) {
            addCriterion("courser_desc =", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescNotEqualTo(String value) {
            addCriterion("courser_desc <>", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescGreaterThan(String value) {
            addCriterion("courser_desc >", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescGreaterThanOrEqualTo(String value) {
            addCriterion("courser_desc >=", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescLessThan(String value) {
            addCriterion("courser_desc <", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescLessThanOrEqualTo(String value) {
            addCriterion("courser_desc <=", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescLike(String value) {
            addCriterion("courser_desc like", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescNotLike(String value) {
            addCriterion("courser_desc not like", value, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescIn(List<String> values) {
            addCriterion("courser_desc in", values, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescNotIn(List<String> values) {
            addCriterion("courser_desc not in", values, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescBetween(String value1, String value2) {
            addCriterion("courser_desc between", value1, value2, "courserDesc");
            return (Criteria) this;
        }

        public Criteria andCourserDescNotBetween(String value1, String value2) {
            addCriterion("courser_desc not between", value1, value2, "courserDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courser
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 02 20:22:34 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}