package com.stuSystem.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScoresExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public ScoresExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScoresIdIsNull() {
            addCriterion("scores_id is null");
            return (Criteria) this;
        }

        public Criteria andScoresIdIsNotNull() {
            addCriterion("scores_id is not null");
            return (Criteria) this;
        }

        public Criteria andScoresIdEqualTo(Integer value) {
            addCriterion("scores_id =", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdNotEqualTo(Integer value) {
            addCriterion("scores_id <>", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdGreaterThan(Integer value) {
            addCriterion("scores_id >", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("scores_id >=", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdLessThan(Integer value) {
            addCriterion("scores_id <", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdLessThanOrEqualTo(Integer value) {
            addCriterion("scores_id <=", value, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdIn(List<Integer> values) {
            addCriterion("scores_id in", values, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdNotIn(List<Integer> values) {
            addCriterion("scores_id not in", values, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdBetween(Integer value1, Integer value2) {
            addCriterion("scores_id between", value1, value2, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresIdNotBetween(Integer value1, Integer value2) {
            addCriterion("scores_id not between", value1, value2, "scoresId");
            return (Criteria) this;
        }

        public Criteria andScoresTcidIsNull() {
            addCriterion("scores_tcId is null");
            return (Criteria) this;
        }

        public Criteria andScoresTcidIsNotNull() {
            addCriterion("scores_tcId is not null");
            return (Criteria) this;
        }

        public Criteria andScoresTcidEqualTo(String value) {
            addCriterion("scores_tcId =", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidNotEqualTo(String value) {
            addCriterion("scores_tcId <>", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidGreaterThan(String value) {
            addCriterion("scores_tcId >", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidGreaterThanOrEqualTo(String value) {
            addCriterion("scores_tcId >=", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidLessThan(String value) {
            addCriterion("scores_tcId <", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidLessThanOrEqualTo(String value) {
            addCriterion("scores_tcId <=", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidLike(String value) {
            addCriterion("scores_tcId like", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidNotLike(String value) {
            addCriterion("scores_tcId not like", value, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidIn(List<String> values) {
            addCriterion("scores_tcId in", values, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidNotIn(List<String> values) {
            addCriterion("scores_tcId not in", values, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidBetween(String value1, String value2) {
            addCriterion("scores_tcId between", value1, value2, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresTcidNotBetween(String value1, String value2) {
            addCriterion("scores_tcId not between", value1, value2, "scoresTcid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidIsNull() {
            addCriterion("scores_stuId is null");
            return (Criteria) this;
        }

        public Criteria andScoresStuidIsNotNull() {
            addCriterion("scores_stuId is not null");
            return (Criteria) this;
        }

        public Criteria andScoresStuidEqualTo(String value) {
            addCriterion("scores_stuId =", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidNotEqualTo(String value) {
            addCriterion("scores_stuId <>", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidGreaterThan(String value) {
            addCriterion("scores_stuId >", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidGreaterThanOrEqualTo(String value) {
            addCriterion("scores_stuId >=", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidLessThan(String value) {
            addCriterion("scores_stuId <", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidLessThanOrEqualTo(String value) {
            addCriterion("scores_stuId <=", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidLike(String value) {
            addCriterion("scores_stuId like", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidNotLike(String value) {
            addCriterion("scores_stuId not like", value, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidIn(List<String> values) {
            addCriterion("scores_stuId in", values, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidNotIn(List<String> values) {
            addCriterion("scores_stuId not in", values, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidBetween(String value1, String value2) {
            addCriterion("scores_stuId between", value1, value2, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresStuidNotBetween(String value1, String value2) {
            addCriterion("scores_stuId not between", value1, value2, "scoresStuid");
            return (Criteria) this;
        }

        public Criteria andScoresResIsNull() {
            addCriterion("scores_res is null");
            return (Criteria) this;
        }

        public Criteria andScoresResIsNotNull() {
            addCriterion("scores_res is not null");
            return (Criteria) this;
        }

        public Criteria andScoresResEqualTo(Double value) {
            addCriterion("scores_res =", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResNotEqualTo(Double value) {
            addCriterion("scores_res <>", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResGreaterThan(Double value) {
            addCriterion("scores_res >", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResGreaterThanOrEqualTo(Double value) {
            addCriterion("scores_res >=", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResLessThan(Double value) {
            addCriterion("scores_res <", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResLessThanOrEqualTo(Double value) {
            addCriterion("scores_res <=", value, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResIn(List<Double> values) {
            addCriterion("scores_res in", values, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResNotIn(List<Double> values) {
            addCriterion("scores_res not in", values, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResBetween(Double value1, Double value2) {
            addCriterion("scores_res between", value1, value2, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresResNotBetween(Double value1, Double value2) {
            addCriterion("scores_res not between", value1, value2, "scoresRes");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeIsNull() {
            addCriterion("scores_intime is null");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeIsNotNull() {
            addCriterion("scores_intime is not null");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeEqualTo(Date value) {
            addCriterion("scores_intime =", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeNotEqualTo(Date value) {
            addCriterion("scores_intime <>", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeGreaterThan(Date value) {
            addCriterion("scores_intime >", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("scores_intime >=", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeLessThan(Date value) {
            addCriterion("scores_intime <", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeLessThanOrEqualTo(Date value) {
            addCriterion("scores_intime <=", value, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeIn(List<Date> values) {
            addCriterion("scores_intime in", values, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeNotIn(List<Date> values) {
            addCriterion("scores_intime not in", values, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeBetween(Date value1, Date value2) {
            addCriterion("scores_intime between", value1, value2, "scoresIntime");
            return (Criteria) this;
        }

        public Criteria andScoresIntimeNotBetween(Date value1, Date value2) {
            addCriterion("scores_intime not between", value1, value2, "scoresIntime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scores
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 02 20:22:34 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scores
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}