package com.stuSystem.manager.pojo;

import java.util.Date;

public class Scores {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.scores_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Integer scoresId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.scores_tcId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private String scoresTcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.scores_stuId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private String scoresStuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.scores_res
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Double scoresRes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.scores_intime
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Date scoresIntime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.scores_id
     *
     * @return the value of scores.scores_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Integer getScoresId() {
        return scoresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.scores_id
     *
     * @param scoresId the value for scores.scores_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setScoresId(Integer scoresId) {
        this.scoresId = scoresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.scores_tcId
     *
     * @return the value of scores.scores_tcId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getScoresTcid() {
        return scoresTcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.scores_tcId
     *
     * @param scoresTcid the value for scores.scores_tcId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setScoresTcid(String scoresTcid) {
        this.scoresTcid = scoresTcid == null ? null : scoresTcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.scores_stuId
     *
     * @return the value of scores.scores_stuId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getScoresStuid() {
        return scoresStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.scores_stuId
     *
     * @param scoresStuid the value for scores.scores_stuId
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setScoresStuid(String scoresStuid) {
        this.scoresStuid = scoresStuid == null ? null : scoresStuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.scores_res
     *
     * @return the value of scores.scores_res
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Double getScoresRes() {
        return scoresRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.scores_res
     *
     * @param scoresRes the value for scores.scores_res
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setScoresRes(Double scoresRes) {
        this.scoresRes = scoresRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.scores_intime
     *
     * @return the value of scores.scores_intime
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Date getScoresIntime() {
        return scoresIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.scores_intime
     *
     * @param scoresIntime the value for scores.scores_intime
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setScoresIntime(Date scoresIntime) {
        this.scoresIntime = scoresIntime;
    }
}