package com.stuSystem.manager.pojo;

import java.util.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_pwd
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_photo
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_sex
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_birthday
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Date teachBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_mobile
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_title
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String teachTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_level
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Integer teachLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_line
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Integer teachLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_enSch
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Date teachEnsch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_lastLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Date teachLastlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teach_regLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private Date teachReglogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_id
     *
     * @return the value of teacher.teach_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachId() {
        return teachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_id
     *
     * @param teachId the value for teacher.teach_id
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachId(String teachId) {
        this.teachId = teachId == null ? null : teachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_name
     *
     * @return the value of teacher.teach_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachName() {
        return teachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_name
     *
     * @param teachName the value for teacher.teach_name
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachName(String teachName) {
        this.teachName = teachName == null ? null : teachName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_pwd
     *
     * @return the value of teacher.teach_pwd
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachPwd() {
        return teachPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_pwd
     *
     * @param teachPwd the value for teacher.teach_pwd
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachPwd(String teachPwd) {
        this.teachPwd = teachPwd == null ? null : teachPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_photo
     *
     * @return the value of teacher.teach_photo
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachPhoto() {
        return teachPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_photo
     *
     * @param teachPhoto the value for teacher.teach_photo
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachPhoto(String teachPhoto) {
        this.teachPhoto = teachPhoto == null ? null : teachPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_sex
     *
     * @return the value of teacher.teach_sex
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachSex() {
        return teachSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_sex
     *
     * @param teachSex the value for teacher.teach_sex
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachSex(String teachSex) {
        this.teachSex = teachSex == null ? null : teachSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_birthday
     *
     * @return the value of teacher.teach_birthday
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Date getTeachBirthday() {
        return teachBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_birthday
     *
     * @param teachBirthday the value for teacher.teach_birthday
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachBirthday(Date teachBirthday) {
        this.teachBirthday = teachBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_mobile
     *
     * @return the value of teacher.teach_mobile
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachMobile() {
        return teachMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_mobile
     *
     * @param teachMobile the value for teacher.teach_mobile
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachMobile(String teachMobile) {
        this.teachMobile = teachMobile == null ? null : teachMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_email
     *
     * @return the value of teacher.teach_email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachEmail() {
        return teachEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_email
     *
     * @param teachEmail the value for teacher.teach_email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachEmail(String teachEmail) {
        this.teachEmail = teachEmail == null ? null : teachEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_title
     *
     * @return the value of teacher.teach_title
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getTeachTitle() {
        return teachTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_title
     *
     * @param teachTitle the value for teacher.teach_title
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachTitle(String teachTitle) {
        this.teachTitle = teachTitle == null ? null : teachTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_level
     *
     * @return the value of teacher.teach_level
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Integer getTeachLevel() {
        return teachLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_level
     *
     * @param teachLevel the value for teacher.teach_level
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachLevel(Integer teachLevel) {
        this.teachLevel = teachLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_line
     *
     * @return the value of teacher.teach_line
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Integer getTeachLine() {
        return teachLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_line
     *
     * @param teachLine the value for teacher.teach_line
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachLine(Integer teachLine) {
        this.teachLine = teachLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_enSch
     *
     * @return the value of teacher.teach_enSch
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Date getTeachEnsch() {
        return teachEnsch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_enSch
     *
     * @param teachEnsch the value for teacher.teach_enSch
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachEnsch(Date teachEnsch) {
        this.teachEnsch = teachEnsch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_lastLogin
     *
     * @return the value of teacher.teach_lastLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Date getTeachLastlogin() {
        return teachLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_lastLogin
     *
     * @param teachLastlogin the value for teacher.teach_lastLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachLastlogin(Date teachLastlogin) {
        this.teachLastlogin = teachLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teach_regLogin
     *
     * @return the value of teacher.teach_regLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public Date getTeachReglogin() {
        return teachReglogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teach_regLogin
     *
     * @param teachReglogin the value for teacher.teach_regLogin
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setTeachReglogin(Date teachReglogin) {
        this.teachReglogin = teachReglogin;
    }
}