package com.stuSystem.manager.pojo;

import java.util.Date;

public class Teachcourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private String tcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private String tcCourser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc-teacher
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private String tcTeacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_level
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Integer tcLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_stuCount
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Integer tcStucount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_start
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Date tcStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachcourse.tc_end
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    private Date tcEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_id
     *
     * @return the value of teachcourse.tc_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getTcId() {
        return tcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_id
     *
     * @param tcId the value for teachcourse.tc_id
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcId(String tcId) {
        this.tcId = tcId == null ? null : tcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_courser
     *
     * @return the value of teachcourse.tc_courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getTcCourser() {
        return tcCourser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_courser
     *
     * @param tcCourser the value for teachcourse.tc_courser
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcCourser(String tcCourser) {
        this.tcCourser = tcCourser == null ? null : tcCourser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc-teacher
     *
     * @return the value of teachcourse.tc-teacher
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public String getTcTeacher() {
        return tcTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc-teacher
     *
     * @param tcTeacher the value for teachcourse.tc-teacher
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcTeacher(String tcTeacher) {
        this.tcTeacher = tcTeacher == null ? null : tcTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_level
     *
     * @return the value of teachcourse.tc_level
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Integer getTcLevel() {
        return tcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_level
     *
     * @param tcLevel the value for teachcourse.tc_level
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcLevel(Integer tcLevel) {
        this.tcLevel = tcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_stuCount
     *
     * @return the value of teachcourse.tc_stuCount
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Integer getTcStucount() {
        return tcStucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_stuCount
     *
     * @param tcStucount the value for teachcourse.tc_stuCount
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcStucount(Integer tcStucount) {
        this.tcStucount = tcStucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_start
     *
     * @return the value of teachcourse.tc_start
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Date getTcStart() {
        return tcStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_start
     *
     * @param tcStart the value for teachcourse.tc_start
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcStart(Date tcStart) {
        this.tcStart = tcStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachcourse.tc_end
     *
     * @return the value of teachcourse.tc_end
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public Date getTcEnd() {
        return tcEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachcourse.tc_end
     *
     * @param tcEnd the value for teachcourse.tc_end
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    public void setTcEnd(Date tcEnd) {
        this.tcEnd = tcEnd;
    }
}