package com.stuSystem.manager.pojo;

public class Courser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courser.courser_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private String courserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courser.courser_name
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private String courserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courser.courser_type
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private Integer courserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courser.courser_desc
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    private String courserDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courser.courser_id
     *
     * @return the value of courser.courser_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getCourserId() {
        return courserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courser.courser_id
     *
     * @param courserId the value for courser.courser_id
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setCourserId(String courserId) {
        this.courserId = courserId == null ? null : courserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courser.courser_name
     *
     * @return the value of courser.courser_name
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getCourserName() {
        return courserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courser.courser_name
     *
     * @param courserName the value for courser.courser_name
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setCourserName(String courserName) {
        this.courserName = courserName == null ? null : courserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courser.courser_type
     *
     * @return the value of courser.courser_type
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public Integer getCourserType() {
        return courserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courser.courser_type
     *
     * @param courserType the value for courser.courser_type
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setCourserType(Integer courserType) {
        this.courserType = courserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courser.courser_desc
     *
     * @return the value of courser.courser_desc
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public String getCourserDesc() {
        return courserDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courser.courser_desc
     *
     * @param courserDesc the value for courser.courser_desc
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    public void setCourserDesc(String courserDesc) {
        this.courserDesc = courserDesc == null ? null : courserDesc.trim();
    }
}