package com.stuSystem.manager.pojo;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_class
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_pwd
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_photo
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_sex
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_mobile
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_email
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private String stuEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_birthday
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Date stuBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_level
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Integer stuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_online
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Integer stuOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_enSch
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Date stuEnsch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_lastLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Date stuLastlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_regLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    private Date stuReglogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_class
     *
     * @return the value of student.stu_class
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_class
     *
     * @param stuClass the value for student.stu_class
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuClass(String stuClass) {
        this.stuClass = stuClass == null ? null : stuClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_pwd
     *
     * @return the value of student.stu_pwd
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuPwd() {
        return stuPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_pwd
     *
     * @param stuPwd the value for student.stu_pwd
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuPwd(String stuPwd) {
        this.stuPwd = stuPwd == null ? null : stuPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_photo
     *
     * @return the value of student.stu_photo
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuPhoto() {
        return stuPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_photo
     *
     * @param stuPhoto the value for student.stu_photo
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuPhoto(String stuPhoto) {
        this.stuPhoto = stuPhoto == null ? null : stuPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_sex
     *
     * @return the value of student.stu_sex
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_sex
     *
     * @param stuSex the value for student.stu_sex
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_mobile
     *
     * @return the value of student.stu_mobile
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuMobile() {
        return stuMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_mobile
     *
     * @param stuMobile the value for student.stu_mobile
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuMobile(String stuMobile) {
        this.stuMobile = stuMobile == null ? null : stuMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_email
     *
     * @return the value of student.stu_email
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getStuEmail() {
        return stuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_email
     *
     * @param stuEmail the value for student.stu_email
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail == null ? null : stuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_birthday
     *
     * @return the value of student.stu_birthday
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Date getStuBirthday() {
        return stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_birthday
     *
     * @param stuBirthday the value for student.stu_birthday
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuBirthday(Date stuBirthday) {
        this.stuBirthday = stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_level
     *
     * @return the value of student.stu_level
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Integer getStuLevel() {
        return stuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_level
     *
     * @param stuLevel the value for student.stu_level
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuLevel(Integer stuLevel) {
        this.stuLevel = stuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_online
     *
     * @return the value of student.stu_online
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Integer getStuOnline() {
        return stuOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_online
     *
     * @param stuOnline the value for student.stu_online
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuOnline(Integer stuOnline) {
        this.stuOnline = stuOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_enSch
     *
     * @return the value of student.stu_enSch
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Date getStuEnsch() {
        return stuEnsch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_enSch
     *
     * @param stuEnsch the value for student.stu_enSch
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuEnsch(Date stuEnsch) {
        this.stuEnsch = stuEnsch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_lastLogin
     *
     * @return the value of student.stu_lastLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Date getStuLastlogin() {
        return stuLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_lastLogin
     *
     * @param stuLastlogin the value for student.stu_lastLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuLastlogin(Date stuLastlogin) {
        this.stuLastlogin = stuLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_regLogin
     *
     * @return the value of student.stu_regLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Date getStuReglogin() {
        return stuReglogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_regLogin
     *
     * @param stuReglogin the value for student.stu_regLogin
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setStuReglogin(Date stuReglogin) {
        this.stuReglogin = stuReglogin;
    }
}