package com.stuSystem.manager.pojo;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.xh
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.xm
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.xb
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.xh
     *
     * @return the value of student.xh
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.xh
     *
     * @param xh the value for student.xh
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.xm
     *
     * @return the value of student.xm
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.xm
     *
     * @param xm the value for student.xm
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.xb
     *
     * @return the value of student.xb
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.xb
     *
     * @param xb the value for student.xb
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbggenerated Wed May 06 16:13:50 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }
}