package com.stuSystem.manager.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public TeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTeachIdIsNull() {
            addCriterion("teach_id is null");
            return (Criteria) this;
        }

        public Criteria andTeachIdIsNotNull() {
            addCriterion("teach_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeachIdEqualTo(String value) {
            addCriterion("teach_id =", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdNotEqualTo(String value) {
            addCriterion("teach_id <>", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdGreaterThan(String value) {
            addCriterion("teach_id >", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdGreaterThanOrEqualTo(String value) {
            addCriterion("teach_id >=", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdLessThan(String value) {
            addCriterion("teach_id <", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdLessThanOrEqualTo(String value) {
            addCriterion("teach_id <=", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdLike(String value) {
            addCriterion("teach_id like", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdNotLike(String value) {
            addCriterion("teach_id not like", value, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdIn(List<String> values) {
            addCriterion("teach_id in", values, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdNotIn(List<String> values) {
            addCriterion("teach_id not in", values, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdBetween(String value1, String value2) {
            addCriterion("teach_id between", value1, value2, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachIdNotBetween(String value1, String value2) {
            addCriterion("teach_id not between", value1, value2, "teachId");
            return (Criteria) this;
        }

        public Criteria andTeachNameIsNull() {
            addCriterion("teach_name is null");
            return (Criteria) this;
        }

        public Criteria andTeachNameIsNotNull() {
            addCriterion("teach_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeachNameEqualTo(String value) {
            addCriterion("teach_name =", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameNotEqualTo(String value) {
            addCriterion("teach_name <>", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameGreaterThan(String value) {
            addCriterion("teach_name >", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameGreaterThanOrEqualTo(String value) {
            addCriterion("teach_name >=", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameLessThan(String value) {
            addCriterion("teach_name <", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameLessThanOrEqualTo(String value) {
            addCriterion("teach_name <=", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameLike(String value) {
            addCriterion("teach_name like", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameNotLike(String value) {
            addCriterion("teach_name not like", value, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameIn(List<String> values) {
            addCriterion("teach_name in", values, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameNotIn(List<String> values) {
            addCriterion("teach_name not in", values, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameBetween(String value1, String value2) {
            addCriterion("teach_name between", value1, value2, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachNameNotBetween(String value1, String value2) {
            addCriterion("teach_name not between", value1, value2, "teachName");
            return (Criteria) this;
        }

        public Criteria andTeachPwdIsNull() {
            addCriterion("teach_pwd is null");
            return (Criteria) this;
        }

        public Criteria andTeachPwdIsNotNull() {
            addCriterion("teach_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andTeachPwdEqualTo(String value) {
            addCriterion("teach_pwd =", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdNotEqualTo(String value) {
            addCriterion("teach_pwd <>", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdGreaterThan(String value) {
            addCriterion("teach_pwd >", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdGreaterThanOrEqualTo(String value) {
            addCriterion("teach_pwd >=", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdLessThan(String value) {
            addCriterion("teach_pwd <", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdLessThanOrEqualTo(String value) {
            addCriterion("teach_pwd <=", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdLike(String value) {
            addCriterion("teach_pwd like", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdNotLike(String value) {
            addCriterion("teach_pwd not like", value, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdIn(List<String> values) {
            addCriterion("teach_pwd in", values, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdNotIn(List<String> values) {
            addCriterion("teach_pwd not in", values, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdBetween(String value1, String value2) {
            addCriterion("teach_pwd between", value1, value2, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPwdNotBetween(String value1, String value2) {
            addCriterion("teach_pwd not between", value1, value2, "teachPwd");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoIsNull() {
            addCriterion("teach_photo is null");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoIsNotNull() {
            addCriterion("teach_photo is not null");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoEqualTo(String value) {
            addCriterion("teach_photo =", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoNotEqualTo(String value) {
            addCriterion("teach_photo <>", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoGreaterThan(String value) {
            addCriterion("teach_photo >", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("teach_photo >=", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoLessThan(String value) {
            addCriterion("teach_photo <", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoLessThanOrEqualTo(String value) {
            addCriterion("teach_photo <=", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoLike(String value) {
            addCriterion("teach_photo like", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoNotLike(String value) {
            addCriterion("teach_photo not like", value, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoIn(List<String> values) {
            addCriterion("teach_photo in", values, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoNotIn(List<String> values) {
            addCriterion("teach_photo not in", values, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoBetween(String value1, String value2) {
            addCriterion("teach_photo between", value1, value2, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachPhotoNotBetween(String value1, String value2) {
            addCriterion("teach_photo not between", value1, value2, "teachPhoto");
            return (Criteria) this;
        }

        public Criteria andTeachSexIsNull() {
            addCriterion("teach_sex is null");
            return (Criteria) this;
        }

        public Criteria andTeachSexIsNotNull() {
            addCriterion("teach_sex is not null");
            return (Criteria) this;
        }

        public Criteria andTeachSexEqualTo(String value) {
            addCriterion("teach_sex =", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexNotEqualTo(String value) {
            addCriterion("teach_sex <>", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexGreaterThan(String value) {
            addCriterion("teach_sex >", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexGreaterThanOrEqualTo(String value) {
            addCriterion("teach_sex >=", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexLessThan(String value) {
            addCriterion("teach_sex <", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexLessThanOrEqualTo(String value) {
            addCriterion("teach_sex <=", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexLike(String value) {
            addCriterion("teach_sex like", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexNotLike(String value) {
            addCriterion("teach_sex not like", value, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexIn(List<String> values) {
            addCriterion("teach_sex in", values, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexNotIn(List<String> values) {
            addCriterion("teach_sex not in", values, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexBetween(String value1, String value2) {
            addCriterion("teach_sex between", value1, value2, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachSexNotBetween(String value1, String value2) {
            addCriterion("teach_sex not between", value1, value2, "teachSex");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayIsNull() {
            addCriterion("teach_birthday is null");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayIsNotNull() {
            addCriterion("teach_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayEqualTo(Date value) {
            addCriterion("teach_birthday =", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayNotEqualTo(Date value) {
            addCriterion("teach_birthday <>", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayGreaterThan(Date value) {
            addCriterion("teach_birthday >", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("teach_birthday >=", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayLessThan(Date value) {
            addCriterion("teach_birthday <", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("teach_birthday <=", value, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayIn(List<Date> values) {
            addCriterion("teach_birthday in", values, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayNotIn(List<Date> values) {
            addCriterion("teach_birthday not in", values, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayBetween(Date value1, Date value2) {
            addCriterion("teach_birthday between", value1, value2, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("teach_birthday not between", value1, value2, "teachBirthday");
            return (Criteria) this;
        }

        public Criteria andTeachMobileIsNull() {
            addCriterion("teach_mobile is null");
            return (Criteria) this;
        }

        public Criteria andTeachMobileIsNotNull() {
            addCriterion("teach_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andTeachMobileEqualTo(String value) {
            addCriterion("teach_mobile =", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileNotEqualTo(String value) {
            addCriterion("teach_mobile <>", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileGreaterThan(String value) {
            addCriterion("teach_mobile >", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileGreaterThanOrEqualTo(String value) {
            addCriterion("teach_mobile >=", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileLessThan(String value) {
            addCriterion("teach_mobile <", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileLessThanOrEqualTo(String value) {
            addCriterion("teach_mobile <=", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileLike(String value) {
            addCriterion("teach_mobile like", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileNotLike(String value) {
            addCriterion("teach_mobile not like", value, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileIn(List<String> values) {
            addCriterion("teach_mobile in", values, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileNotIn(List<String> values) {
            addCriterion("teach_mobile not in", values, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileBetween(String value1, String value2) {
            addCriterion("teach_mobile between", value1, value2, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachMobileNotBetween(String value1, String value2) {
            addCriterion("teach_mobile not between", value1, value2, "teachMobile");
            return (Criteria) this;
        }

        public Criteria andTeachEmailIsNull() {
            addCriterion("teach_email is null");
            return (Criteria) this;
        }

        public Criteria andTeachEmailIsNotNull() {
            addCriterion("teach_email is not null");
            return (Criteria) this;
        }

        public Criteria andTeachEmailEqualTo(String value) {
            addCriterion("teach_email =", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailNotEqualTo(String value) {
            addCriterion("teach_email <>", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailGreaterThan(String value) {
            addCriterion("teach_email >", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailGreaterThanOrEqualTo(String value) {
            addCriterion("teach_email >=", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailLessThan(String value) {
            addCriterion("teach_email <", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailLessThanOrEqualTo(String value) {
            addCriterion("teach_email <=", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailLike(String value) {
            addCriterion("teach_email like", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailNotLike(String value) {
            addCriterion("teach_email not like", value, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailIn(List<String> values) {
            addCriterion("teach_email in", values, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailNotIn(List<String> values) {
            addCriterion("teach_email not in", values, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailBetween(String value1, String value2) {
            addCriterion("teach_email between", value1, value2, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachEmailNotBetween(String value1, String value2) {
            addCriterion("teach_email not between", value1, value2, "teachEmail");
            return (Criteria) this;
        }

        public Criteria andTeachTitleIsNull() {
            addCriterion("teach_title is null");
            return (Criteria) this;
        }

        public Criteria andTeachTitleIsNotNull() {
            addCriterion("teach_title is not null");
            return (Criteria) this;
        }

        public Criteria andTeachTitleEqualTo(String value) {
            addCriterion("teach_title =", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleNotEqualTo(String value) {
            addCriterion("teach_title <>", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleGreaterThan(String value) {
            addCriterion("teach_title >", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleGreaterThanOrEqualTo(String value) {
            addCriterion("teach_title >=", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleLessThan(String value) {
            addCriterion("teach_title <", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleLessThanOrEqualTo(String value) {
            addCriterion("teach_title <=", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleLike(String value) {
            addCriterion("teach_title like", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleNotLike(String value) {
            addCriterion("teach_title not like", value, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleIn(List<String> values) {
            addCriterion("teach_title in", values, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleNotIn(List<String> values) {
            addCriterion("teach_title not in", values, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleBetween(String value1, String value2) {
            addCriterion("teach_title between", value1, value2, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachTitleNotBetween(String value1, String value2) {
            addCriterion("teach_title not between", value1, value2, "teachTitle");
            return (Criteria) this;
        }

        public Criteria andTeachLevelIsNull() {
            addCriterion("teach_level is null");
            return (Criteria) this;
        }

        public Criteria andTeachLevelIsNotNull() {
            addCriterion("teach_level is not null");
            return (Criteria) this;
        }

        public Criteria andTeachLevelEqualTo(Integer value) {
            addCriterion("teach_level =", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelNotEqualTo(Integer value) {
            addCriterion("teach_level <>", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelGreaterThan(Integer value) {
            addCriterion("teach_level >", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("teach_level >=", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelLessThan(Integer value) {
            addCriterion("teach_level <", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelLessThanOrEqualTo(Integer value) {
            addCriterion("teach_level <=", value, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelIn(List<Integer> values) {
            addCriterion("teach_level in", values, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelNotIn(List<Integer> values) {
            addCriterion("teach_level not in", values, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelBetween(Integer value1, Integer value2) {
            addCriterion("teach_level between", value1, value2, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("teach_level not between", value1, value2, "teachLevel");
            return (Criteria) this;
        }

        public Criteria andTeachLineIsNull() {
            addCriterion("teach_line is null");
            return (Criteria) this;
        }

        public Criteria andTeachLineIsNotNull() {
            addCriterion("teach_line is not null");
            return (Criteria) this;
        }

        public Criteria andTeachLineEqualTo(Integer value) {
            addCriterion("teach_line =", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineNotEqualTo(Integer value) {
            addCriterion("teach_line <>", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineGreaterThan(Integer value) {
            addCriterion("teach_line >", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineGreaterThanOrEqualTo(Integer value) {
            addCriterion("teach_line >=", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineLessThan(Integer value) {
            addCriterion("teach_line <", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineLessThanOrEqualTo(Integer value) {
            addCriterion("teach_line <=", value, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineIn(List<Integer> values) {
            addCriterion("teach_line in", values, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineNotIn(List<Integer> values) {
            addCriterion("teach_line not in", values, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineBetween(Integer value1, Integer value2) {
            addCriterion("teach_line between", value1, value2, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachLineNotBetween(Integer value1, Integer value2) {
            addCriterion("teach_line not between", value1, value2, "teachLine");
            return (Criteria) this;
        }

        public Criteria andTeachEnschIsNull() {
            addCriterion("teach_enSch is null");
            return (Criteria) this;
        }

        public Criteria andTeachEnschIsNotNull() {
            addCriterion("teach_enSch is not null");
            return (Criteria) this;
        }

        public Criteria andTeachEnschEqualTo(Date value) {
            addCriterion("teach_enSch =", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschNotEqualTo(Date value) {
            addCriterion("teach_enSch <>", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschGreaterThan(Date value) {
            addCriterion("teach_enSch >", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschGreaterThanOrEqualTo(Date value) {
            addCriterion("teach_enSch >=", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschLessThan(Date value) {
            addCriterion("teach_enSch <", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschLessThanOrEqualTo(Date value) {
            addCriterion("teach_enSch <=", value, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschIn(List<Date> values) {
            addCriterion("teach_enSch in", values, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschNotIn(List<Date> values) {
            addCriterion("teach_enSch not in", values, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschBetween(Date value1, Date value2) {
            addCriterion("teach_enSch between", value1, value2, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachEnschNotBetween(Date value1, Date value2) {
            addCriterion("teach_enSch not between", value1, value2, "teachEnsch");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginIsNull() {
            addCriterion("teach_lastLogin is null");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginIsNotNull() {
            addCriterion("teach_lastLogin is not null");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginEqualTo(Date value) {
            addCriterion("teach_lastLogin =", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginNotEqualTo(Date value) {
            addCriterion("teach_lastLogin <>", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginGreaterThan(Date value) {
            addCriterion("teach_lastLogin >", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginGreaterThanOrEqualTo(Date value) {
            addCriterion("teach_lastLogin >=", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginLessThan(Date value) {
            addCriterion("teach_lastLogin <", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginLessThanOrEqualTo(Date value) {
            addCriterion("teach_lastLogin <=", value, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginIn(List<Date> values) {
            addCriterion("teach_lastLogin in", values, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginNotIn(List<Date> values) {
            addCriterion("teach_lastLogin not in", values, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginBetween(Date value1, Date value2) {
            addCriterion("teach_lastLogin between", value1, value2, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachLastloginNotBetween(Date value1, Date value2) {
            addCriterion("teach_lastLogin not between", value1, value2, "teachLastlogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginIsNull() {
            addCriterion("teach_regLogin is null");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginIsNotNull() {
            addCriterion("teach_regLogin is not null");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginEqualTo(Date value) {
            addCriterion("teach_regLogin =", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginNotEqualTo(Date value) {
            addCriterion("teach_regLogin <>", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginGreaterThan(Date value) {
            addCriterion("teach_regLogin >", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginGreaterThanOrEqualTo(Date value) {
            addCriterion("teach_regLogin >=", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginLessThan(Date value) {
            addCriterion("teach_regLogin <", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginLessThanOrEqualTo(Date value) {
            addCriterion("teach_regLogin <=", value, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginIn(List<Date> values) {
            addCriterion("teach_regLogin in", values, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginNotIn(List<Date> values) {
            addCriterion("teach_regLogin not in", values, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginBetween(Date value1, Date value2) {
            addCriterion("teach_regLogin between", value1, value2, "teachReglogin");
            return (Criteria) this;
        }

        public Criteria andTeachRegloginNotBetween(Date value1, Date value2) {
            addCriterion("teach_regLogin not between", value1, value2, "teachReglogin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated do_not_delete_during_merge Thu May 07 10:50:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table teacher
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}