package com.stuSystem.manager.mapper;

import com.stuSystem.manager.pojo.Announce;
import com.stuSystem.manager.pojo.AnnounceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnnounceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int countByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int deleteByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int deleteByPrimaryKey(Integer annouId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int insert(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int insertSelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    List<Announce> selectByExample(AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    Announce selectByPrimaryKey(Integer annouId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Announce record, @Param("example") AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int updateByExample(@Param("record") Announce record, @Param("example") AnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int updateByPrimaryKeySelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Thu May 07 10:50:38 CST 2020
     */
    int updateByPrimaryKey(Announce record);
}