package com.stuSystem.manager.mapper;

import com.stuSystem.manager.pojo.Teachcourse;
import com.stuSystem.manager.pojo.TeachcourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeachcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int countByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int deleteByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int deleteByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int insert(Teachcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int insertSelective(Teachcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    List<Teachcourse> selectByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    Teachcourse selectByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") Teachcourse record, @Param("example") TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int updateByExample(@Param("record") Teachcourse record, @Param("example") TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int updateByPrimaryKeySelective(Teachcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 09 08:44:08 CST 2020
     */
    int updateByPrimaryKey(Teachcourse record);
}