package com.stuSystem.manager.mapper;

import com.stuSystem.manager.custpojo.CstmTc;
import com.stuSystem.manager.pojo.TcParam;
import com.stuSystem.manager.pojo.Teachcourse;
import com.stuSystem.manager.pojo.TeachcourseExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TeachcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int countByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int deleteByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int deleteByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int insert(Teachcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int insertSelective(Teachcourse record);


    /**
     * 自定义查询
     * 根据教师ID查询该教师教授课程的授课ID和课程名称
     * @param teachId
     * @return
     */
    List<Map<String,String>> selectIdAndNameByTeachId(@Param("teachId") String teachId);

    /**
     * 自定义查询
     * 根据授课ID查询相关联的课程信息
     * @param tcId
     * @return
     */
    CstmTc selectAssoCourseByTcId(@Param("tcId") String tcId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    List<Teachcourse> selectByExample(TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    Teachcourse selectByPrimaryKey(String tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Teachcourse record, @Param("example") TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int updateByExample(@Param("record") Teachcourse record, @Param("example") TeachcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int updateByPrimaryKeySelective(Teachcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachcourse
     *
     * @mbggenerated Tue Jun 02 20:22:34 CST 2020
     */
    int updateByPrimaryKey(Teachcourse record);

    /**
     * 更新学生人数
     * @param tcParam
     * @return
     */
    int updateStuCount(@Param("tcParam")TcParam tcParam);
}